;;; ue-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ue.el

(put 'ue-global-mode 'globalized-minor-mode t)
(defvar ue-global-mode nil "\
Non-nil if Ue-Global mode is enabled.
See the `ue-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `ue-global-mode'.")
(custom-autoload 'ue-global-mode "ue" nil)
(autoload 'ue-global-mode "ue" "\
Toggle Ue mode in all buffers.
With prefix ARG, enable Ue-Global mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Ue mode is enabled in all buffers where `ue-on' would do it.

See `ue-mode' for more information on Ue mode.

(fn &optional ARG)" t)
(register-definition-prefixes "ue" '("ue-"))

;;; End of scraped data

(provide 'ue-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ue-autoloads.el ends here
