;;; javelin-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from javelin.el

(autoload 'javelin-go-to "javelin" "\
Go to specific file or buffer of the javelin by JAVELIN-NUMBER.

(fn JAVELIN-NUMBER)" t)
(autoload 'javelin-go-to-1 "javelin" "\
Go to the buffer at position 1 of the javelin." t)
(autoload 'javelin-go-to-2 "javelin" "\
Go to the buffer at position 2 of the javelin." t)
(autoload 'javelin-go-to-3 "javelin" "\
Go to the buffer at position 3 of the javelin." t)
(autoload 'javelin-go-to-4 "javelin" "\
Go to the buffer at position 4 of the javelin." t)
(autoload 'javelin-go-to-5 "javelin" "\
Go to the buffer at position 5 of the javelin." t)
(autoload 'javelin-go-to-6 "javelin" "\
Go to the buffer at position 6 of the javelin." t)
(autoload 'javelin-go-to-7 "javelin" "\
Go to the buffer at position 7 of the javelin." t)
(autoload 'javelin-go-to-8 "javelin" "\
Go to the buffer at position 8 of the javelin." t)
(autoload 'javelin-go-to-9 "javelin" "\
Go to the buffer at position 9 of the javelin." t)
(autoload 'javelin-delete "javelin" "\
Delete an item of the javelin. JAVELIN-NUMBER: Position to delete.

(fn JAVELIN-NUMBER)" t)
(autoload 'javelin-delete-1 "javelin" "\
Delete position 1 of the javelin." t)
(autoload 'javelin-delete-2 "javelin" "\
Delete position 2 of the javelin." t)
(autoload 'javelin-delete-3 "javelin" "\
Delete position 3 of the javelin." t)
(autoload 'javelin-delete-4 "javelin" "\
Delete position 4 of the javelin." t)
(autoload 'javelin-delete-5 "javelin" "\
Delete position 5 of the javelin." t)
(autoload 'javelin-delete-6 "javelin" "\
Delete position 6 of the javelin." t)
(autoload 'javelin-delete-7 "javelin" "\
Delete position 7 of the javelin." t)
(autoload 'javelin-delete-8 "javelin" "\
Delete position 8 of the javelin." t)
(autoload 'javelin-delete-9 "javelin" "\
Delete position 9 of the javelin." t)
(autoload 'javelin-assign-to "javelin" "\
Assign the current buffer to a specific position in javelin.
JAVELIN-NUMBER: The position (1-9) to assign the current buffer to.

(fn JAVELIN-NUMBER)" t)
(autoload 'javelin-assign-to-1 "javelin" "\
Assign current buffer to position 1 of the javelin." t)
(autoload 'javelin-assign-to-2 "javelin" "\
Assign current buffer to position 2 of the javelin." t)
(autoload 'javelin-assign-to-3 "javelin" "\
Assign current buffer to position 3 of the javelin." t)
(autoload 'javelin-assign-to-4 "javelin" "\
Assign current buffer to position 4 of the javelin." t)
(autoload 'javelin-assign-to-5 "javelin" "\
Assign current buffer to position 5 of the javelin." t)
(autoload 'javelin-assign-to-6 "javelin" "\
Assign current buffer to position 6 of the javelin." t)
(autoload 'javelin-assign-to-7 "javelin" "\
Assign current buffer to position 7 of the javelin." t)
(autoload 'javelin-assign-to-8 "javelin" "\
Assign current buffer to position 8 of the javelin." t)
(autoload 'javelin-assign-to-9 "javelin" "\
Assign current buffer to position 9 of the javelin." t)
(autoload 'javelin-go-or-assign-to "javelin" "\
Go to javelin position if occupied, otherwise assign current buffer to it.
JAVELIN-NUMBER: The position (1-9) to go to or assign.
With FORCE (or prefix arg [universal-argument]), always assign even if
position is occupied.

(fn JAVELIN-NUMBER &optional FORCE)")
(autoload 'javelin-go-or-assign-to-1 "javelin" "\
Go to or assign position 1 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-2 "javelin" "\
Go to or assign position 2 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-3 "javelin" "\
Go to or assign position 3 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-4 "javelin" "\
Go to or assign position 4 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-5 "javelin" "\
Go to or assign position 5 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-6 "javelin" "\
Go to or assign position 6 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-7 "javelin" "\
Go to or assign position 7 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-8 "javelin" "\
Go to or assign position 8 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-or-assign-to-9 "javelin" "\
Go to or assign position 9 of the javelin.
With FORCE (or prefix arg \\[universal-argument]), always assign.

(fn &optional FORCE)" t)
(autoload 'javelin-go-to-next "javelin" "\
Go to the next buffer in javelin." t)
(autoload 'javelin-go-to-prev "javelin" "\
Go to the previous buffer in javelin." t)
(autoload 'javelin-add-file "javelin" "\
Add current buffer to javelin at the next available position." t)
(autoload 'javelin-toggle-quick-menu "javelin" "\
Open quick menu to select a javelined buffer." t)
(autoload 'javelin-clear "javelin" "\
Clear all javelin positions." t)
(autoload 'javelin-clear-all "javelin" "\
Delete all javelin position namespaces." t)
(autoload 'javelin-minor-mode "javelin" "\
Minor mode for quick buffer navigation with javelin.

Provides keybindings for jumping to javelined buffers:
  M-1 to M-9: Go to position (or assign if empty, \\[universal-argument] to force assign)
  M-0 0: Clear all positions
  M-0 1-9: Delete position
  M--: Toggle quick menu

This is a minor mode.  If called interactively, toggle the `Javelin
minor mode' mode.  If the prefix argument is positive, enable the mode,
and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `javelin-minor-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-javelin-minor-mode 'globalized-minor-mode t)
(defvar global-javelin-minor-mode nil "\
Non-nil if Global Javelin minor mode is enabled.
See the `global-javelin-minor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-javelin-minor-mode'.")
(custom-autoload 'global-javelin-minor-mode "javelin" nil)
(autoload 'global-javelin-minor-mode "javelin" "\
Toggle Javelin minor mode in all buffers.
With prefix ARG, enable Global Javelin minor mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Javelin minor mode is enabled in all buffers where `(lambda nil
(javelin-minor-mode 1))' would do it.

See `javelin-minor-mode' for more information on Javelin minor mode.

(fn &optional ARG)" t)
(register-definition-prefixes "javelin" '("javelin-"))

;;; End of scraped data

(provide 'javelin-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; javelin-autoloads.el ends here
